name: publish-pages
run-name: ${{ github.actor }} is publishing pages
on:
    - push
    - workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4
            - name: "Copy files"
              run: |
                mkdir _site
                cp acat.png gpgkey.txt index.html _site
                cp -r .well-known _site
            - name: "Upload artifacts"
              uses: actions/upload-pages-artifact@v3.0.0
    deploy:
        needs: build
        permissions: 
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-22.04
        steps:
            - name: Deploy to GH Pages
              id: deployment
              uses: actions/deploy-pages@v4